'use strict';
const BaseDivorceDecreeTemplate = require('../../core/BaseDivorceDecreeTemplate');
class AbiaDivorceDecreeTemplate extends BaseDivorceDecreeTemplate {
  constructor() { super(); this.state = 'AB_NG'; this.stateName = 'Abia'; this.countryCode = 'NG'; this.documentTitle = 'DECREE NISI'; try { this.metadata = require('./metadata.json'); } catch (e) { this.metadata = null; } this.requiredFields = ['petitionerName', 'respondentName', 'state', 'county', 'caseNumber', 'marriageDate']; this.formatting = { fontSize: '12pt', fontFamily: 'Times New Roman', lineHeight: '1.5', margin: '1in', paperSize: 'A4' }; }
  getCaseNumberLabel() { return 'Suit No.'; }
  getDefaultCourt(county) { return `HIGH COURT OF ABIA STATE — ${(county || '[JUDICIAL DIVISION]').toUpperCase()} JUDICIAL DIVISION`; }
  generateHeader() { return 'IN THE HIGH COURT OF ABIA STATE'; }
  generateVenue(county) { return `${(county || '[JUDICIAL DIVISION]').toUpperCase()} JUDICIAL DIVISION`; }
  generateCaseCaption(d) { const cn = (d.court || this.getDefaultCourt(d.county)).toUpperCase(); const num = d.caseNumber || '[SUIT NUMBER]'; const p = (d.petitionerName || '[PETITIONER NAME]').toUpperCase(); const r = (d.respondentName || '[RESPONDENT NAME]').toUpperCase(); return { courtName: cn, caseNumber: d.caseNumber, petitioner: d.petitionerName, respondent: d.respondentName, formatted: `IN THE ${cn}\n\nSuit No. ${num}\n\nIN THE MATTER OF THE MATRIMONIAL CAUSES ACT, CAP M7 LFN 2004\n\nBETWEEN:\n\n${p}\nPetitioner\n\n— AND —\n\n${r}\nRespondent` }; }
  generatePropertyDivisionSection(d) { return { title: 'ANCILLARY ORDERS — PROPERTY', items: [{ content: d.hasProperty === false ? 'No ancillary property order necessary.' : 'Each party retains property in their possession unless otherwise ordered (MCA s.70-73).', type: 'order' }], type: 'property' }; }
  generateChildCustodySection(d) { if (d.hasMinorChildren === false || !d.children || d.children.length === 0) return null; const items = [{ content: 'Custody ordered in the best interests of the child(ren) (MCA s.71).', type: 'finding' }]; d.children.forEach((c, i) => items.push({ content: `${i + 1}. ${typeof c === 'string' ? c : (c.name || '[CHILD]')}`, type: 'child_item' })); items.push({ content: `${d.primaryCustodian || d.petitionerName || 'The Petitioner'} shall have custody (MCA s.71).`, type: 'order' }); return { title: 'CUSTODY', items, type: 'custody' }; }
  generateChildSupportSection(d) { if (d.hasMinorChildren === false || !d.children || d.children.length === 0) return null; return { title: 'CHILD MAINTENANCE', items: [{ content: 'The Respondent shall pay reasonable child maintenance (MCA s.70).', type: 'order' }], type: 'child_support' }; }
  generateSpousalSupportSection(d) { if (!d.spousalSupportAwarded && !d.spousalSupportWaived) return null; return { title: 'SPOUSAL MAINTENANCE', items: [{ content: d.spousalSupportWaived ? 'Neither party applied for maintenance.' : `Maintenance of NGN ${d.spousalSupportAmount || '[AMOUNT]'} per month ordered (MCA s.70).`, type: 'order' }], type: 'spousal_support' }; }
  generateFinalOrdersSection() { return { title: 'FINAL ORDERS', items: [{ content: 'IT IS HEREBY DECREED that the marriage is dissolved by this Decree Nisi.', type: 'order' }, { content: 'This Decree Nisi becomes Decree Absolute after 3 months (MCA s.58).', type: 'order' }], type: 'final_orders' }; }
}
module.exports = AbiaDivorceDecreeTemplate;
