// templates/states/edo/DivorceDecreeTemplate.js
'use strict';
const BaseDivorceDecreeTemplate = require('../../core/BaseDivorceDecreeTemplate');
const { resolveCustodyArrangement, resolvePrimaryResidenceName } = require('../../core/parenting');
class EdoDivorceDecreeTemplate extends BaseDivorceDecreeTemplate {
  // Nigerian terminology (see templates/core/terminology.js): the caption is the
  // court-name line + suit number; parties are Petitioner/Respondent under the
  // Matrimonial Causes Act 1970; High Courts sit in judicial divisions, not
  // counties. No "STATE OF"/"COUNTY OF" caption lines, no "X County" body phrasing.
  constructor() { super(); this.state = 'ED'; this.stateName = 'Edo'; this.countryCode = 'NG'; this.terminology = { ...this.terminology, jurisdictionLabel: null, districtLabel: null, districtStyle: 'plain', jurisdictionTerm: 'State', districtTerm: 'Judicial division', districtPlaceholder: '[JUDICIAL DIVISION]', filerLabel: 'Petitioner', responderLabel: 'Respondent', selfRepresentedLabel: 'Self-Represented' }; this.documentTitle = 'DECREE NISI'; try { this.metadata = require('./metadata.json'); } catch (e) { this.metadata = null; } this.requiredFields = ['petitionerName', 'respondentName', 'state', 'county', 'caseNumber', 'marriageDate']; this.formatting = { fontSize: '12pt', fontFamily: 'Times New Roman', lineHeight: '1.5', margin: '1in', paperSize: 'A4' }; }
  getCaseNumberLabel() { return 'Suit No.'; }
  getDefaultCourt(county) { return `HIGH COURT OF EDO STATE — ${(county || '[JUDICIAL DIVISION]').toUpperCase()} JUDICIAL DIVISION`; }
  generateHeader() { return 'IN THE HIGH COURT OF EDO STATE'; }
  generateVenue(county) { return `${(county || '[JUDICIAL DIVISION]').toUpperCase()} JUDICIAL DIVISION`; }
  generateCaseCaption(d) { const cn = (d.court || this.getDefaultCourt(d.county)).toUpperCase(); const num = d.caseNumber || '[SUIT NUMBER]'; const p = (d.petitionerName || '[PETITIONER NAME]').toUpperCase(); const r = (d.respondentName || '[RESPONDENT NAME]').toUpperCase(); return { courtName: cn, caseNumber: d.caseNumber, petitioner: d.petitionerName, respondent: d.respondentName, formatted: `IN THE ${cn}\n\nSuit No. ${num}\n\nIN THE MATTER OF THE MATRIMONIAL CAUSES ACT, CAP M7 LFN 2004\n\nBETWEEN:\n\n${p}\nPetitioner\n\n— AND —\n\n${r}\nRespondent` }; }
  generatePropertyDivisionSection(d) { const items = []; items.push({ content: d.hasProperty === false ? 'No ancillary property order necessary.' : 'The Court has considered property matters pursuant to MCA s.70-73. Each party retains property in their possession unless otherwise ordered.', type: d.hasProperty === false ? 'finding' : 'order' }); return { title: 'ANCILLARY ORDERS — PROPERTY', items, type: 'property' }; }
  generateChildCustodySection(d) { if (d.hasMinorChildren === false || !d.children || d.children.length === 0) return null; const items = []; items.push({ content: 'Custody ordered in the best interests of the child(ren) (MCA s.71):', type: 'finding' }); d.children.forEach((c, i) => { const info = typeof c === 'string' ? c : `${c.name || '[CHILD]'}, born ${this.formatDate(c.birthDate) || '[DOB]'}`; items.push({ content: `${i + 1}. ${info}`, type: 'child_item' }); }); const custody = resolveCustodyArrangement(d); const residenceName = resolvePrimaryResidenceName(d); let soleCustodianName = null; const custodyKind = custody.explicit ? custody.kind : 'unspecified'; if (custodyKind === 'joint') { items.push({ content: `IT IS ORDERED that ${d.petitionerName || 'the Petitioner'} and ${d.respondentName || 'the Respondent'} shall have joint custody pursuant to MCA s.71.`, type: 'order' }); } else if (custodyKind === 'sole_petitioner' || custodyKind === 'sole_respondent' || custodyKind === 'legacy_sole') { soleCustodianName = custodyKind === 'sole_petitioner' ? (d.petitionerName || 'the Petitioner') : custodyKind === 'sole_respondent' ? (d.respondentName || 'the Respondent') : (resolvePrimaryResidenceName(d) || d.petitionerName || 'the Petitioner'); items.push({ content: `IT IS ORDERED that ${soleCustodianName} shall have custody pursuant to MCA s.71.`, type: 'order' }); } else { items.push({ content: 'IT IS ORDERED that the parties shall exercise legal custody and decision-making responsibility for the child(ren) as agreed by the parties: [ARRANGEMENT — set out the parties\' decision-making agreement].', type: 'order' }); } if (custodyKind !== 'joint' && residenceName && residenceName !== soleCustodianName) { items.push({ content: `IT IS ORDERED that the child(ren) shall primarily reside with ${residenceName}.`, type: 'order' }); } return { title: 'CUSTODY OF CHILD(REN)', items, type: 'custody' }; }
  generateChildSupportSection(d) { if (d.hasMinorChildren === false || !d.children || d.children.length === 0) return null; return { title: 'CHILD MAINTENANCE', items: [{ content: 'IT IS ORDERED pursuant to MCA s.70 that the Respondent shall pay reasonable maintenance for the child(ren).', type: 'order' }], type: 'child_support' }; }
  generateSpousalSupportSection(d) { if (!d.spousalSupportAwarded && !d.spousalSupportWaived) return null; const items = []; if (d.spousalSupportWaived) items.push({ content: 'Neither party applied for maintenance under MCA s.70.', type: 'order' }); else items.push({ content: `IT IS ORDERED that ${d.spousalSupportPayor || 'the Respondent'} shall pay maintenance of NGN ${d.spousalSupportAmount || '[AMOUNT]'} per month (MCA s.70).`, type: 'order' }); return { title: 'SPOUSAL MAINTENANCE', items, type: 'spousal_support' }; }
  generateFinalOrdersSection() { return { title: 'FINAL ORDERS', items: [{ content: 'IT IS HEREBY DECREED that the marriage is dissolved by this Decree Nisi.', type: 'order' }, { content: 'This Decree Nisi becomes Decree Absolute after 3 months (MCA s.58).', type: 'order' }, { content: 'The Decree Nisi becomes absolute automatically by force of law after 3 months; no application is required (MCA s.58). Where there are children under 16, it does not become absolute until the Court has made the declaration required by MCA s.57.', type: 'order' }], type: 'final_orders' }; }
}
module.exports = EdoDivorceDecreeTemplate;
