'use strict';
const BaseDivorcePetitionTemplate = require('../../core/BaseDivorcePetitionTemplate');
class EnuguDivorcePetitionTemplate extends BaseDivorcePetitionTemplate {
  constructor() { super(); this.state = 'EN'; this.stateName = 'Enugu'; this.countryCode = 'NG'; this.documentTitle = 'PETITION FOR DISSOLUTION OF MARRIAGE'; try { this.metadata = require('./metadata.json'); } catch (e) { this.metadata = null; } this.requiredFields = ['petitionerName', 'respondentName', 'state', 'county', 'marriageDate', 'groundsForDivorce']; this.residencyRequirements = { stateMonths: 0, countyDays: 0, description: 'Either party must be domiciled in Nigeria (MCA s.2). A wife ordinarily resident for 3 years is deemed domiciled (MCA s.7(b)). Any person domiciled in Nigeria may file in the High Court of any state (MCA s.2(3)); the Enugu High Court is the usual venue when either party resides in the state.' }; this.waitingPeriod = { days: 0, description: 'Decree Nisi -> 3 months -> Decree Absolute (MCA s.58; where children under 16, subject to the s.57 declaration).' }; this.formatting = { fontSize: '12pt', fontFamily: 'Times New Roman', lineHeight: '1.5', margin: '1in', paperSize: 'A4' }; }
  getCaseNumberLabel() { return 'Suit No.'; }
  getDefaultCourt(county) { return `HIGH COURT OF ENUGU STATE — ${(county || '[JUDICIAL DIVISION]').toUpperCase()} JUDICIAL DIVISION`; }
  generateCaseCaption(d) { const cn = (d.court || this.getDefaultCourt(d.county)).toUpperCase(); const num = d.caseNumber || '[SUIT NUMBER]'; const p = (d.petitionerName || '[PETITIONER NAME]').toUpperCase(); const r = (d.respondentName || '[RESPONDENT NAME]').toUpperCase(); return { courtName: cn, caseNumber: d.caseNumber, petitioner: d.petitionerName, respondent: d.respondentName, formatted: [`IN THE ${cn}`, '', `Suit No. ${num}`, '', 'IN THE MATTER OF THE MATRIMONIAL CAUSES ACT, CAP M7 LFN 2004', '', 'BETWEEN:', '', p, 'Petitioner', '', 'AND', '', r, 'Respondent'].join('\n') }; }
  getJurisdictionStatement() { return 'The Petitioner/Respondent is domiciled in Nigeria per MCA s.2 and may institute proceedings in the High Court of any State (MCA s.2(3)). The Petitioner resides within Enugu State, making this Honourable Court the appropriate venue.'; }
  getVenueReason(d) { return `the Petitioner resides within the ${d.county || '[JUDICIAL DIVISION]'} Judicial Division of Enugu State`; }
  generateReliefSection(d) { const items = []; items.push({ number: null, content: 'THE PETITIONER HUMBLY PRAYS that the Honourable Court grant the following relief:', type: 'relief_intro' }); const ri = ['A Decree Nisi for dissolution (MCA s.15);', 'That the Decree Nisi be made absolute after 3 months (MCA s.58);']; if (d.hasMinorChildren || (d.children && d.children.length > 0)) { ri.push('Custody (MCA s.71);'); ri.push('Child maintenance (MCA s.70);'); } if (d.spousalSupportRequested || d.requestSpousalSupport) ri.push('Spousal maintenance (MCA s.70);'); ri.push('Such further orders as the Court deems just.'); ri.forEach((r, i) => items.push({ number: null, content: r, type: 'relief_item', style: 'letter', letter: String.fromCharCode(97 + i) })); return { title: 'RELIEF SOUGHT', items, nextParagraphNumber: d._paragraphNum || 15 }; }
  getVerificationText(d) { return `I, ${d.petitionerName || '[PETITIONER NAME]'}, make oath and state that the facts in this Petition are true to the best of my knowledge.`; }
  getGroundsText(g) { const s = (g || 'separation_consent').toLowerCase(); if (s.includes('adultery')) return 'Since the marriage the Respondent has committed adultery and the Petitioner finds it intolerable to live with the Respondent (MCA s.15(2)(b)).'; if (s.includes('intolerable') || s.includes('behaviour') || s.includes('cruelty')) return 'Since the marriage the Respondent has behaved in such a way that the Petitioner cannot reasonably be expected to live with the Respondent (MCA s.15(2)(c)).'; if (s.includes('desertion')) return 'The Respondent has deserted the Petitioner for a continuous period of at least 1 year immediately preceding this Petition (MCA s.15(2)(d)).'; if (s.includes('separation_no_consent') || s.includes('three')) return 'The parties have lived apart for a continuous period of at least 3 years immediately preceding this Petition (MCA s.15(2)(f)).'; if (s.includes('refusal') || s.includes('consummate')) return 'The Respondent has wilfully and persistently refused to consummate the marriage (MCA s.15(2)(a)).'; if (s.includes('restitution')) return 'Failure to comply with restitution decree for 1+ year (MCA s.15(2)(g)).'; if (s.includes('death') || s.includes('absent') || s.includes('presumption')) return 'The Respondent has been absent for such time and in such circumstances as to provide reasonable grounds for presuming death (MCA s.15(2)(h)); absence of 7+ years with no reason to believe the Respondent alive suffices (MCA s.16(2)(a)).'; return 'The parties have lived apart for a continuous period of at least 2 years immediately preceding this Petition and the Respondent does not object to a decree (MCA s.15(2)(e)).'; }
}
module.exports = EnuguDivorcePetitionTemplate;
